lista = [
    {
        "id": 1,
        "nombre": "Tandi",
        "edad": 54,
        "gender": "F",
        "email": "tlabusch0@newyorker.com",
    },
    {
        "id": 2,
        "nombre": "Nelie",
        "edad": 57,
        "gender": "F",
        "email": "nboullen1@lycos.com",
    },
    {
        "id": 3,
        "nombre": "Pansy",
        "edad": 53,
        "gender": "F",
        "email": "psaltsberg2@gmpg.org",
    },
    {
        "id": 4,
        "nombre": "Ollie",
        "edad": 25,
        "gender": "F",
        "email": "oion3@histats.com",
    },
    {
        "id": 5,
        "nombre": "Marlene",
        "edad": 36,
        "gender": "F",
        "email": "mmicco4@google.com.br",
    },
    {
        "id": 6,
        "nombre": "Crysta",
        "edad": 41,
        "gender": "F",
        "email": "cfrazer5@guardian.co.uk",
    },
    {
        "id": 7,
        "nombre": "Thaine",
        "edad": 44,
        "gender": "M",
        "email": "tclardge6@wordpress.org",
    },
    {
        "id": 8,
        "nombre": "Brander",
        "edad": 36,
        "gender": "M",
        "email": "bstenbridge7@mail.ru",
    },
    {"id": 9, "nombre": "Fawne", "edad": 52, "gender": "F", "email": "fgreim8@hud.gov"},
    {
        "id": 10,
        "nombre": "Patty",
        "edad": 58,
        "gender": "M",
        "email": "pbelli9@furl.net",
    },
    {
        "id": 11,
        "nombre": "Colas",
        "edad": 42,
        "gender": "M",
        "email": "cmcgairla@gizmodo.com",
    },
    {
        "id": 12,
        "nombre": "Janene",
        "edad": 61,
        "gender": "F",
        "email": "jsarleb@ask.com",
    },
    {
        "id": 13,
        "nombre": "Amanda",
        "edad": 23,
        "gender": "F",
        "email": "aduinkerkc@dedecms.com",
    },
    {"id": 14, "nombre": "Seka", "edad": 60, "gender": "F", "email": "ssoled@wsj.com"},
    {
        "id": 15,
        "nombre": "Mahala",
        "edad": 54,
        "gender": "F",
        "email": "mmincinie@tripod.com",
    },
]
