lista = [
    {"id": 1, "nombre": "Stefan", "edad": 65, "gender": "M", "sector": "Services"},
    {
        "id": 2,
        "nombre": "Katey",
        "edad": 58,
        "gender": "F",
        "sector": "Research and Development",
    },
    {
        "id": 3,
        "nombre": "Sherie",
        "edad": 57,
        "gender": "F",
        "sector": "Human Resources",
    },
    {"id": 4, "nombre": "Shae", "edad": 42, "gender": "M", "sector": "Marketing"},
    {"id": 5, "nombre": "Clevie", "edad": 29, "gender": "M", "sector": "Services"},
    {
        "id": 6,
        "nombre": "Shay",
        "edad": 27,
        "gender": "M",
        "sector": "Business Development",
    },
    {"id": 7, "nombre": "Ursa", "edad": 52, "gender": "F", "sector": "Marketing"},
    {"id": 8, "nombre": "Webb", "edad": 25, "gender": "M", "sector": "Human Resources"},
    {"id": 9, "nombre": "Taite", "edad": 58, "gender": "M", "sector": "Accounting"},
    {"id": 10, "nombre": "Kaye", "edad": 39, "gender": "F", "sector": "Marketing"},
    {"id": 11, "nombre": "Nataline", "edad": 59, "gender": "F", "sector": "Support"},
    {"id": 12, "nombre": "Ricca", "edad": 56, "gender": "F", "sector": "Training"},
    {"id": 13, "nombre": "Ronnie", "edad": 63, "gender": "M", "sector": "Accounting"},
    {
        "id": 14,
        "nombre": "Antonio",
        "edad": 44,
        "gender": "M",
        "sector": "Research and Development",
    },
    {
        "id": 15,
        "nombre": "Denys",
        "edad": 29,
        "gender": "M",
        "sector": "Research and Development",
    },
    {"id": 16, "nombre": "Trev", "edad": 23, "gender": "M", "sector": "Support"},
    {
        "id": 17,
        "nombre": "Curran",
        "edad": 57,
        "gender": "M",
        "sector": "Business Development",
    },
    {
        "id": 18,
        "nombre": "Berkly",
        "edad": 24,
        "gender": "M",
        "sector": "Human Resources",
    },
    {"id": 19, "nombre": "Alanah", "edad": 27, "gender": "F", "sector": "Sales"},
    {
        "id": 20,
        "nombre": "Shandra",
        "edad": 55,
        "gender": "F",
        "sector": "Business Development",
    },
]
