lista = [
    {"id": 1, "nombre": "Diana", "edad": 52, "email": "ddrivers0@homestead.com"},
    {"id": 2, "nombre": "Erinna", "edad": 54, "email": "eeede1@java.com"},
    {
        "id": 3,
        "nombre": "Rafferty",
        "edad": 20,
        "email": "rbenting2@huffingpost.com",
    },
    {"id": 4, "nombre": "Hunter", "edad": 46, "email": "hthorogood3@noaa.gov"},
    {"id": 5, "nombre": "Ariel", "edad": 40, "email": "alange4@posterous.com"},
    {"id": 6, "nombre": "Nicky", "edad": 60, "email": "nstocking5@psu.edu"},
    {"id": 7, "nombre": "Pepe", "edad": 52, "email": "pfellibrand6@a8.net"},
    {"id": 8, "nombre": "Rianon", "edad": 30, "email": "rfoulser7@com.com"},
    {"id": 9, "nombre": "Dolph", "edad": 46, "email": "dbernlin8@tripadvisor.com"},
    {"id": 10, "nombre": "Quintus", "edad": 32, "email": "qofford9@zdnet.com"},
    {"id": 11, "nombre": "Edmon", "edad": 49, "email": "ethursfielda@lulu.com"},
    {"id": 12, "nombre": "Kyle", "edad": 51, "email": "kscrivinb@ucla.edu"},
    {"id": 13, "nombre": "Skippy", "edad": 52, "email": "sleportc@cbsnews.com"},
    {"id": 14, "nombre": "Heall", "edad": 24, "email": "hleyband@cocolog-nifty.com"},
    {"id": 15, "nombre": "Jaquelyn", "edad": 48, "email": "jpinocke@biglobe.ne.jp"},
    {"id": 16, "nombre": "Georgetta", "edad": 31, "email": "ggarritf@ow.ly"},
    {"id": 17, "nombre": "Padriac", "edad": 48, "email": "pspellessyg@twitpic.com"},
    {"id": 18, "nombre": "Alexia", "edad": 31, "email": "amatusovskyh@1und1.de"},
    {"id": 19, "nombre": "Lissa", "edad": 24, "email": "lpechai@amazon.com"},
    {"id": 20, "nombre": "Mallorie", "edad": 52, "email": "mdiggj@walmart.com"},
]
